server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      #路由id
      - id: user-service-route
        #代理的服务地址
        uri: http://127.0.0.1:9000, http://127.0.0.1:9999
        #路由断言
        predicates:
        - Path=/ext/**, /majiang/ds-user/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
